### ISSUE TITLE
Resolving Docker Image Pull Error for `huggingface/text-generation-inference`

### ISSUE THREAD

**Issue by HydraTechnologies-ops** [NVIDIA/workbench-example-hybrid-rag#18]
If you're encountering an error while pulling the `latest` tag of the `huggingface/text-generation-inference` Docker image, follow these steps to resolve it:

#### Steps to Fix

1. **Find the Specific Version:**
   - Visit the [Hugging Face Docker Repository](https://github.com/huggingface/text-generation-inference/pkgs/container/text-generation-inference) and select a specific version or SHA for AMD instead of using `latest`.

2. **Update the `spec.yaml` File:**
   - Navigate to your `spec.yaml` file and locate the `environment` section (line 21).
   - Replace `latest` with the specific version or SHA. For example, update it as follows:
     ```yaml
     environment:
       base:
         registry: ghcr.io
         image: huggingface/text-generation-inference:sha-f3c5d7d@sha256:7c169c536de65dbdb867302aedf9ad0a7472df5d7c7dfd85c080037215b18c16
         build_timestamp: "20231011102429"
         name: TGI
         supported_architectures:
         - amd64
         cuda_version: "11.8"
         description: The huggingface text-generation-interface base container
         entrypoint_script: ""
     ```

3. **Clear Cache and Rebuild:**
   - On the NVIDIA AI Workstation, click on "Clear cache and build" to rebuild the container with the correct image version.

This process should resolve the issue and allow you to successfully pull and use the desired Docker image.

---
